### PR TITLE
upgrade marked dev dependency

### PR DESCRIPTION
**Pull request by marrony**
An attempt to fix the security issue

We can also wait a fix for this https://github.com/jsdoc3/jsdoc/issues/1489

### CODE REVIEW

**Comment by erickpintor** [comment]
I'm fine either waiting of merging this. I'd just put a comment there explaining the situation since we don't use this dependency in our project.

**Comment by marrony** [comment]
You mean put a comment in the `package.json` file? It's not allowed, not anymore.

**Comment by erickpintor** [comment]
🤦‍♂️

**Comment by ashfire908** [comment]
This was handled in https://github.com/fauna/faunadb-js/pull/149, closing.

**Pull request closed without merging**
