### PR TITLE
Change release images for stable images

### PR DESCRIPTION
**Pull request by BrunoQuaresma**
### Notes
- This fixes the pipeline
[Jira Ticket](https://faunadb.atlassian.net/browse/FE-272)

### How to test
- Pipeline should be green

### CODE REVIEW

**Comment by BrunoQuaresma** [comment]
Even stable versions should be failing right now because the fix is only on nightly at this moment.

**Comment by fauna-ryanharris** [comment]
@BrunoQuaresma So this is just changing the Docker image we use for tests from `release` to `stable`?

**Comment by fauna-rodrigo** [comment]
I believe those types of changes can go directly to master

**Comment by BrunoQuaresma** [comment]
@fauna-ryan yeap.

**Comment by BrunoQuaresma** [comment]
@fauna-rodrigo I agree!

**Pull request merged**
