### PR TITLE
Release 2.5.0

### PR DESCRIPTION
**Pull request by bitbckt**

### CODE REVIEW

**Comment by erickpintor** [comment]
The PR looks good. Although I'd feel more comfortable if we fix the failing tests for node 4 and 6. If we still support them. @marrony what do you think? Those missing polyfills might happen in the browser too, right?

**Comment by marrony** [comment]
🤦‍♂️ I don't believe node 4 and 6 doesn't have support for `Object.values`. I was so obvious to me given it support `Object.keys`

**Comment by erickpintor** [comment]
I think there are a few drivers that also doesn't support it. I think we should fix it.

**Comment by bitbckt** [comment]
Is there a ticket for this problem?

**Comment by marrony** [comment]
@erickpintor What other drivers?

**Comment by erickpintor** [comment]
I'm sorry. I meant a few *browsers*.

**Comment by sprsquish** [comment]
pulled internally

**Pull request closed without merging**
