### PR TITLE
fix: updates to stream types

### PR DESCRIPTION
**Pull request by ecwyne**
Types for `client.stream()` callback handlers had incorrect number of arguments. This PR also adds types for `client.stream.document()` and correctly allows `snapshot` events in `client.stream.document()` and not in `client.stream()`

### CODE REVIEW

**Comment by ecwyne** [comment]
Here's a small reproduction running against `v4.0.0`

https://codesandbox.io/s/wispy-grass-izf2d?file=/src/index.ts

**Comment by ChronSyn** [comment]
Any chance we can get some movement on this?

This seems to allow streaming on Node - Not sure of potential side effects, but as it stands, it's currently not possible to use streaming on Node (due to `.document` not being defined in `client.stream`, and `snapshot` throwing 'unrecognized event type').

**Comment by tigger9flow** [comment]
Hey, @ecwyne!
Thank you for your contribution, changes look good to me! One issue with the `.document` method I've fixed in this PR - https://github.com/fauna/faunadb-js/pull/439. So there're merge conflicts for your changes due to this. Could you please resolve them so that I could merge your changes as well?

**Review by fireridlle — APPROVED** [review]

**Review by erickpintor — APPROVED** [review]
LGTM

**Pull request merged**
